name: CI/CD Pipeline for Web Shop on Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform support
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Set up Node.js (example if using Node.js for the app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies and run tests
      - name: Install dependencies
        run: |
          npm install
          npm test
